repos:
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.1.1
  hooks:
    - id: conventional-pre-commit
      stages: [ commit-msg ]

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      args: [--config=./configs/.flake8]

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black
      args: [--config=./configs/pyproject.toml]