[tool.black]
line-length = 120
exclude = '''
    /(
        \.git
      | \.mypy_cache
      | \.pytest_cache
      | \.tox
      | build
      | dist
      | venv
      | .github
      | configs
    )/
'''

