[tool.black]
line-length = 120
exclude = .git,__pycache__,docs/source/conf.py,old,build,dist,venv,env

[flake8]
max-line-length = 120
ignore = E203, E266, E501, W503, F403, F401
exclude = .git,__pycache__,docs/source/conf.py,old,build,dist,venv,env